<img src="http://www.numpy.org/_static/numpy_logo.png" width="300">

---
`Nota: Si crees que este notebook necesita algún cambio no dudes en contribuir a su desarrollo.`

---

<img src="https://imgs.xkcd.com/comics/matrix_transform.png" width="350">


# ¿Qué es NumPy?

NumPy es una librería externa de Python diseñada específicamente para el cálculo científico que facilita el trabajo eficiente con vectores, matrices, números aleatorios, cálculos matemáticos y operaciones de álgebra lineal entre otras cosas.

Habíamos mencionado en la introducción a Python que los lenguages interpretados no son computacionalmente eficientes, ni son rápidos ni gestionan optimamente la memoria. Para superar este inconveniente se pueden programar librerías que trabajan como envoltorios de Python para módulos compilados en otros lenguages. Este es el caso de NumPy cuyo nucleo está programado, y por lo tanto compilado, con C. Además NumPy puede servirnos como interpretador de librerías en C o Fortran para poder invocarlas desde nuestro script en Python.

Puede que NumPy sea la librería de Python más popular. La mayoría de librerías que puedes encontrar tiene a NumPy como dependencia.

# ¿Cómo se instala?

NumPy suele instalarse automáticamente como dependencia con cualquier librería. No obstante, si no tienes NumPy ya instalado en tu entorno de conda:

```bash
conda install numpy
```

## ¿Cómo se usa?

### Importando Numpy

Existe el convenio de importar NumPy con el alias `np`. Esto mismo sucede con otras librerías, que por su frecuente uso recomiendan un alias de pocos caracteres para invocarlo tecleando poco.

In [1]:
import numpy as np

### Vectores

El objeto más sencillo y popular de NumPy es su vector (`ndarray`). Puedes pensar que un `ndarray`, del inglés *n-dimensional array*, es como una lista o una tupla, pero es mucho más que eso. Es una de las maneras más eficientes de manejar datos en memoria y operar con ellos.

Veamos primero como convertir una lista a un `ndarray`:

In [5]:
una_lista = [2,4,6,8,10]

In [6]:
un_vector = np.array(una_lista)

In [7]:
type(un_vector)

numpy.ndarray

In [8]:
un_vector

array([ 2,  4,  6,  8, 10])

In [9]:
print(un_vector)

[ 2  4  6  8 10]


A diferencia de las listas y tuplas, los `ndarray` no son 'expandibles', pero esto los hace eficientes en memoria y de rápida lectura.

In [10]:
# Esto quizá es lo único que puedes echar de menos de trabajar con listas.
# Ya que nose puede hacer con ndarrays.
una_lista.append(12)
print(una_lista)

[2, 4, 6, 8, 10, 12]


Los `ndarrays` tiene una forma fija:

In [11]:
un_vector.shape

(5,)

Podemos inicializar vectores de forma o dimensión deseada sin necesidad de recurrir a una lista:

In [16]:
vec_1 = np.empty(10)

In [17]:
vec_1.shape

(10,)

In [18]:
vec_1

array([6.94741422e-310, 4.82337433e+228, 6.14415221e-144, 1.16097020e-028,
       9.72163297e-072, 6.36600788e-062, 1.08516211e-042, 3.97062373e+246,
       1.16318408e-028, 4.18127829e-062])

El método `np.empty()` reserva el espacio en memoria que aloja el vector, pero no se ocupa de inicializarlo con ningún valor. Es por eso que si lo leemos, antes de haber asignado valores, su contenido es meramente ruido.

Para inizializar algo directamente con valores cero podemos usar `np.zeros()`, y para hacerlo con unos podemos usar `np.ones()`.

In [26]:
vec_1 = np.zeros(6)
vec_2 = np.ones(8)

In [27]:
vec_1

array([0., 0., 0., 0., 0., 0.])

In [28]:
vec_2

array([1., 1., 1., 1., 1., 1., 1., 1.])

Al igual que las variables de Python, los vectores `ndarray` pueden ser de números enteros, de coma flotante, de doble precisión, de carácteres, variables lógicas, etc. Puedes checar [aquí](https://www.numpy.org/devdocs/user/basics.types.html) la lista de posibles tipos.

In [31]:
vec_1.dtype

dtype('float64')

In [35]:
vector_auxiliar = np.zeros(4,dtype=bool)
print(vector_auxiliar)

[False False False False]


In [36]:
vector_auxiliar = np.zeros(4,dtype=int)
print(vector_auxiliar)

[0 0 0 0]


In [41]:
vector_auxiliar = np.zeros(4,dtype=complex)
print(vector_auxiliar)

[0.+0.j 0.+0.j 0.+0.j 0.+0.j]


In [44]:
vector_auxiliar = np.zeros(4,dtype='float64')
print(vector_auxiliar)

[0. 0. 0. 0.]


In [46]:
vector_auxiliar = np.zeros(4,dtype='S3') # para str
print(vector_auxiliar)

[b'' b'' b'' b'']


Estos objetos tienen también métodos y atributos muy útiles. Hemos visto `shape`, pero hay muchos más. 

In [48]:
dir(vec_1)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_e

Por ejemplo vamos a ver `max`, `argmax`,`mean` o `std`:

In [50]:
vec_1 = np.array([6.0, 10.0, 2.0, 5.0, 7.0, 5.0], dtype=float)
print(vec_1)

[ 6. 10.  2.  5.  7.  5.]


In [51]:
help(vec_1.max)

Help on built-in function max:

max(...) method of numpy.ndarray instance
    a.max(axis=None, out=None, keepdims=False)
    
    Return the maximum along a given axis.
    
    Refer to `numpy.amax` for full documentation.
    
    See Also
    --------
    numpy.amax : equivalent function



In [56]:
vec_1.max() # devuelve el máximo valor tomado por el vector

10.0

In [53]:
help(vec_1.argmax)

Help on built-in function argmax:

argmax(...) method of numpy.ndarray instance
    a.argmax(axis=None, out=None)
    
    Return indices of the maximum values along the given axis.
    
    Refer to `numpy.argmax` for full documentation.
    
    See Also
    --------
    numpy.argmax : equivalent function



In [57]:
vec_1.argmax() # devuelve la posición en la que se encuentra el valor máximo

1

In [59]:
help(vec_1.mean)

Help on built-in function mean:

mean(...) method of numpy.ndarray instance
    a.mean(axis=None, dtype=None, out=None, keepdims=False)
    
    Returns the average of the array elements along given axis.
    
    Refer to `numpy.mean` for full documentation.
    
    See Also
    --------
    numpy.mean : equivalent function



In [60]:
vec_1.mean() # devuelve la media aritmética

5.833333333333333

In [63]:
help(vec_1.std)

Help on built-in function std:

std(...) method of numpy.ndarray instance
    a.std(axis=None, dtype=None, out=None, ddof=0, keepdims=False)
    
    Returns the standard deviation of the array elements along given axis.
    
    Refer to `numpy.std` for full documentation.
    
    See Also
    --------
    numpy.std : equivalent function



In [62]:
vec_1.std() # devuelve la desviación estandard

2.4094720491334933

### Matrices y vectores multidimensionales

Al comienzo de la sección pasada hemos revelado que `ndarray` viene del inglés *n-dimensional array* (vector n-dimensional, en español). Probablemente sospeches que en realidad podíamos haber definido un objeto `ndarray` de cualquier forma y dimensiones.

In [64]:
matriz = np.zeros((3,3),dtype=int)

In [69]:
matriz.shape

(3, 3)

In [65]:
matriz

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [67]:
otra_matriz = np.ones((2,4))

In [70]:
otra_matriz.shape

(2, 4)

In [68]:
otra_matriz

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [72]:
la_matriz_transpuesta = otra_matriz.T

In [73]:
la_matriz_transpuesta.shape

(4, 2)

In [74]:
la_matriz_transpuesta

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [75]:
un_tensor_de_rango_3 = np.zeros((2,3,5),dtype=bool)

In [76]:
un_tensor_de_rango_3.shape

(2, 3, 5)

In [77]:
un_tensor_de_rango_3

array([[[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]],

       [[False, False, False, False, False],
        [False, False, False, False, False],
        [False, False, False, False, False]]])

In [78]:
un_tensor_de_rango_5 = np.zeros((2,3,2,4,3))

In [79]:
un_tensor_de_rango_5.shape

(2, 3, 2, 4, 3)

In [80]:
un_tensor_de_rango_5

array([[[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]]],



       [[[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        [[[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]],

         [[0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.],
          [0., 0., 0.]]],


        

### Indexado y cortes en `ndarray`

Veamos como podemos acceder a los elementos de un `ndarray`:

In [82]:
vector = np.array([4,2,6,1,8,9,3])

In [83]:
vector[0]

4

In [84]:
vector[3]

1

In [85]:
vector[-1]

3

In [86]:
vector[-4]

1

In [88]:
vector[[1,2,4,5]] # podemos también usar listas de índices

array([2, 6, 8, 9])

In [89]:
matriz = np.zeros((3,3),dtype=int)

In [90]:
matriz[0,0] = 5
matriz[1,2] = 2
matriz [2,[0,1]] = 1

In [91]:
matriz

array([[5, 0, 0],
       [0, 0, 2],
       [1, 1, 0]])

Puedo delimitar cortes y fragmentar definiendo regiones. Para esto usamos el símbolo ':'.

In [93]:
vector = np.array([10, 9, 8, 7, 6, 5, 4, 3])

In [95]:
vector[:] # sólo con ':' no estamos estableciendo límites en esta dimensión

array([10,  9,  8,  7,  6,  5,  4,  3])

In [96]:
vector[2:]

array([8, 7, 6, 5, 4, 3])

In [98]:
vector[:4]

array([10,  9,  8,  7])

In [99]:
vector[2:4]

array([8, 7])

In [100]:
vector[-2:]

array([4, 3])

In [101]:
vector[-4:-1]

array([6, 5, 4])

Podemos también decidir cada cuento saco valores en el corte con un segundo símbolo ':'.

In [104]:
vector[::]

array([10,  9,  8,  7,  6,  5,  4,  3])

In [105]:
vector[::2]

array([10,  8,  6,  4])

In [110]:
vector[::3]

array([10,  7,  4])

In [107]:
vector[1:6:]

array([9, 8, 7, 6, 5])

In [108]:
vector[1:6:2]

array([9, 7, 5])

In [116]:
vector[-1:-6:-2]

array([3, 5, 7])

Y esto es extensible a `ndarray`s de veras multidimensionales.

In [120]:
un_tensor = np.zeros((2,4,7))

In [121]:
un_tensor

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

In [122]:
un_tensor[0,1,3] = 8.0

In [123]:
un_tensor[1,2,:] = -10.0

In [124]:
un_tensor[0,2:3,1:7:2] = 1.0

In [130]:
un_tensor[:,0,6] = 4

In [131]:
un_tensor

array([[[  0.,   0.,   0.,   0.,   0.,   0.,   4.],
        [  0.,   0.,   0.,   8.,   0.,   0.,   0.],
        [  0.,   1.,   0.,   1.,   0.,   1.,   0.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.]],

       [[  0.,   0.,   0.,   0.,   0.,   0.,   4.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.],
        [-10., -10., -10., -10., -10., -10., -10.],
        [  0.,   0.,   0.,   0.,   0.,   0.,   0.]]])

In [132]:
un_tensor[0]

array([[0., 0., 0., 0., 0., 0., 4.],
       [0., 0., 0., 8., 0., 0., 0.],
       [0., 1., 0., 1., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [133]:
un_tensor[0,1,:]

array([0., 0., 0., 8., 0., 0., 0.])

In [134]:
un_tensor[:,0,2:4]

array([[0., 0.],
       [0., 0.]])

El resultado de indexar o cortar es un nuevo `ndarray`. Así que podemos también aplicar los métodos y atributos que vimos en la sección anterior:

In [136]:
un_tensor[0].max()

8.0

In [137]:
un_tensor[:,0,2:4].mean()

0.0

### Copias o vistas de un `ndarray`. O cómo mover únicamente el puntero.

Este punto es muy relevante y no tenerlo presente puede crear desastrosos errores de dificil detección en tu código. Mejor que comenzar explicándo la diferencia entre una copia y un objeto que apunta a otro, vamos a dejar tu solo o sola comiences a inferirlo en el siguiente ejemplo con listas:

In [140]:
a = [0,1,2]
b = a
b[1] = -7

print(a)
print(b)

[0, -7, 2]
[0, -7, 2]


In [141]:
a = [0,1,2]
b = a.copy()
b[1] = -7

print(a)
print(b)

[0, 1, 2]
[0, -7, 2]


¿Entiendes la diferencia? Python es un lenguage de punteros. Esto significa que un objeto está compuesto por el nombre de la variable (`a` o `b`), su valor almacenado en un segmento de la memoria física de la computadora ([0,1,2] en el caso inicial de `a`), y la dirección o puntero de dicho segmento. Es decir, cuando invocamos `a` la computadora mira cuál es la dirección (o puntero) del segmento físico de memoria y comienza a leer su contenido (el valor de la variable).

En Python podemos acceder a la dirección o puntero de una variable y sacarlo por pantalla:

In [142]:
id(a)

140619379062984

Vamos a ayudarnos del método `id` que nos ofrece la dirección del objeto para darle un segundo vistazo a los ejemplos anteriores:

In [148]:
a = [0,1,2]
b = a
print('La dirección de a es:', id(a))
print('La dirección de b es:', id(b))
print(' ')

b[1] = -7

print('El valor de a es:', a)
print('La valor de b es:', b)

La dirección de a es: 140619379063432
La dirección de b es: 140619379063432
 
El valor de a es: [0, -7, 2]
La valor de b es: [0, -7, 2]


In [149]:
a = [0,1,2]
b = a.copy()
print('La dirección de a es:', id(a))
print('La dirección de b es:', id(b))
print(' ')

b[1] = -7

print('El valor de a es:', a)
print('La valor de b es:', b)

La dirección de a es: 140619379063496
La dirección de b es: 140619391628616
 
El valor de a es: [0, 1, 2]
La valor de b es: [0, -7, 2]


En el primer caso, el símbolo '=' crea un objeto `b` que apunta al mismo segmento de memoria. A esto lo podemos llamar 'vista' o 'puntero', ya que sólo se diferencia de `a` en el nombre.

En el segundo caso, `a.copy()` está generando una copia real física: un duplicado del segmento de memoria de `a` en otra región del espacio memoria y por lo tanto con otra dirección. Al hacer `b = a.copy()`, le estamos asignando al nombre de variable `b`, ese nuevo espacio de memoria. Esto se llama 'copia'.

Con un `ndarray` sucede exactamente lo mismo, con un pequeño matiz que veremos más adelante y que aunque te parezca molesto, resulta muy util.

In [150]:
a = np.array([2,4,6])
b = a
print('La dirección de a es:', id(a))
print('La dirección de b es:', id(b))
print(' ')

b[2] = 0

print('El valor de a es:', a)
print('La valor de b es:', b)

La dirección de a es: 140619379148640
La dirección de b es: 140619379148640
 
El valor de a es: [2 4 0]
La valor de b es: [2 4 0]


In [151]:
a = np.array([2,4,6])
b = a.copy()
print('La dirección de a es:', id(a))
print('La dirección de b es:', id(b))
print(' ')

b[2] = 0

print('El valor de a es:', a)
print('La valor de b es:', b)

La dirección de a es: 140619379149520
La dirección de b es: 140619379149040
 
El valor de a es: [2 4 6]
La valor de b es: [2 4 0]


El matiz que comentabamos anteriormente es que los `ndarray` nos permiten generar nuevas 'vistas' que apuntan a regiones definidas por cortes:

In [152]:
a = np.array([[2,2,2],[4,4,4],[6,6,6]],dtype=int)

In [153]:
a

array([[2, 2, 2],
       [4, 4, 4],
       [6, 6, 6]])

In [154]:
a.shape

(3, 3)

In [155]:
b = a[1:,1:]

In [156]:
b

array([[4, 4],
       [6, 6]])

In [157]:
b.shape

(2, 2)

In [158]:
b[:,:] = 0

In [161]:
b

array([[0, 0],
       [0, 0]])

In [162]:
a

array([[2, 2, 2],
       [4, 0, 0],
       [6, 0, 0]])

In [163]:
b[0,0] = 1

In [164]:
b

array([[1, 0],
       [0, 0]])

In [165]:
a

array([[2, 2, 2],
       [4, 1, 0],
       [6, 0, 0]])

In [166]:
a[2,:] = -1

In [167]:
a

array([[ 2,  2,  2],
       [ 4,  1,  0],
       [-1, -1, -1]])

In [168]:
b

array([[ 1,  0],
       [-1, -1]])

Cuando se quiera duplicar un objeto `ndarray` generando una copia independiente, hay que recordar que se debe recurrir al método `ndarray.copy()`.

Probablemente ahora entiendas la siguiente viñeta cómica de xkcd:

<img src="https://imgs.xkcd.com/comics/pointers.png" width="250">

### Álgebra básica para operar con `ndarrays`

Veamos la sintaxis de operaciones sencillas con `ndarrays` que transforman o devuelven otros `ndarrays`

In [171]:
vec_1 = np.array([0,1,2],dtype=int)
vec_2 = np.array([10,9,8],dtype=int)
print(vec_1,vec_2)

[0 1 2] [10  9  8]


In [172]:
vec_3 = vec_1 + 1
print(vec_3)

[1 2 3]


In [175]:
vec_3 = vec_1*2
print(vec_3)

[0 2 4]


In [176]:
vec_3 = vec_1**2
print(vec_3)

[0 1 4]


In [179]:
vec_3 = np.log2(vec_1+1) # Numpy tiene además una gran colección de operaciones matemáticas
print(vec_3)

[0.        1.        1.5849625]


In [180]:
vec_3 = np.cos(vec_1)
print(vec_3)

[ 1.          0.54030231 -0.41614684]


In [181]:
vec_3 = vec_1+vec_2
print(vec_3)

[10 10 10]


In [184]:
vec_3 = vec_1*vec_2 # Esta multiplicación es elemento a elemento
print(vec_3)

[ 0  9 16]


In [185]:
vec_3 = np.dot(vec_1,vec_2) # Esta es la multiplicación vectorial conocida como 'dot product'
print(vec_3)

25


In [197]:
vec_3 = np.matmul(vec_1,vec_2) # Esta es la multiplicación matricial, 'dot product' si son vectores
print(vec_3)

25


In [201]:
vec_3 = np.cross(vec_1.T,vec_2) # Esta es el producto vectorial, o 'cross product' en inglés.
print(vec_3)

[-10  20 -10]


In [204]:
mat_1 = np.array([[0,1,2],[0,1,2],[0,1,2]],dtype=int)
mat_2 = np.ones((3,3),dtype=int)*2
print(mat_1)
print(mat_2)

[[0 1 2]
 [0 1 2]
 [0 1 2]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [208]:
mat_3 = mat_1+10
print(mat_3)

[[10 11 12]
 [10 11 12]
 [10 11 12]]


In [209]:
mat_3 = mat_1*2
print(mat_3)

[[0 2 4]
 [0 2 4]
 [0 2 4]]


In [210]:
mat_3 = mat_1+mat_2
print(mat_3)

[[2 3 4]
 [2 3 4]
 [2 3 4]]


In [212]:
mat_3 = mat_1*mat_2 # Esta operación es elemento a elemento: aij*bij
print(mat_3)

[[0 2 4]
 [0 2 4]
 [0 2 4]]


In [214]:
mat_3 = np.dot(mat_1,mat_2) # esta operación es el producto matricial
print(mat_3)

[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [215]:
mat_3 = np.matmul(mat_1,mat_2) # esta operación es el producto matricial
print(mat_3)

[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [217]:
mat_3 = np.matmul(mat_1,vec_1) # esta operación es el producto matricial
print(mat_3)

[5 5 5]


# Más recursos útiles 

El propósito de este notebook es ser un documento únicamente introductorio. Puedes encontrar -o contribuir añadiendo- más información útil en el siguiente listado:

## Documentación

## Tutoriales
http://www.learnpython.org/es/Numpy%20Arrays   
http://www.iac.es/sieinvens/python-course/source/numpy.html   
https://geekytheory.com/pylab-parte-2-datos-basicos-numpy
http://damianavila.github.io/Python-Cientifico-HCC/3_NumPy.html